- dev-portal/src/services/api-catalog.js
We need a way to PUT /apig//marketplace-subscriptions/ to tell the dev lambdas to check the user's marketplace id and match them up to both our cognito id and subscribe them to the plan they purchased.
> Adds function to confirm a marketplace subscription

- package.json
Installing local dependencies either copies the module to node_modules/ or creates a symlink within node_modules/ depending on the NPM version. Symlinks won't work because they don't get sent up to S3 and a module is lost in the process. This change explicitly packages up the lambdas/_common module as a Tarball (using npm pack) and then is installed into node_modules/ ensuring that the full module directory is available
> Explicitly package up lambdas/_common module before installing

- CODEOWNERS
Previously, @alantan's approval was required for any commit that touched
the README. Since we edit the README semi-frequently, we'd rather let
team members' approve PRs. @alantan is still included as a CODEOWNER for
the README so he'll receive email notifications & can provide input.
> Add whole team to CODEOWNERS for README

- README.md
- lambdas/catalog-updater/index.js
There are several changes in this commit:
First, YAML files should be supported again in the catalog.
Second, usage plan throttle and quota information is exposed to the
front-end in the catalog. Closes #87.
Third, users can name their file API:STAGE.json or API:STAGE.yaml,
and their apiId and stageName will be extracted from the filename. An
example might be the file 'catalog/a1e3cf8aqu:production.json'. If the
file is not named in this format, we fall back to trying to extract the
apiId and stageName from the swagger's host and basePath fields. This
will fail if the api has a custom domain associated with it.
> Fixes for catalog updater

- lambdas/backend/catalog/index.js
- lambdas/backend/express-server.js
Send a specific cloudwatch log and return usable data if the catalog.json file doesn't exit.
> don't return bad catalog data if no catalog.json

- README.md
This was initially postponed because I hoped we could pass a query into
the deploy command. It appears that CFN deploys do not produce output on
query, though... :(
> Add how to get dev portal URL to README

- README.md
- cloudformation/template.yaml
The user can now provide a domain name (associated with an ACM cert) as
a parameter override to build out a cloudfront distribution and
associated route53 records. If the parameter override is not provided,
the dev portal is built as previously without a cloudfront distribution
or route53 records.
> Add custom domain name support

- README.md
- cloudformation/template.yaml
The cloudfront distribution set up by the CFN stack didn't properly use
the customers' ACM cert, instead using a wildcard cert (*.cloudfront).
This caused browsers to show an 'untrusted SSL cert' error on visiting
the page.
> Fix 'untrusted SSL cert' error on custom domain setup

- cloudformation/template.yaml
This will cause it to have a readable name (e.g.,
three-dev-portal-backend-api) instead of being named after the timestamp
(Imported on 2018-10-16T16:5...).
> Add title to backend API

- README.md
- cloudformation/template.yaml
Some customers will have their own nameserver hosting and would rather
not use Route53. This option will support them out of the box.
> Allow users to skip Route53 during domain name creation

- cloudformation/template.yaml
Dev portal hosted on a custom domain used to redirect to an XML page
instead of showing the (client-side) 404. This was because the
cloudfront origin was set to s3's bucket URL, not s3's website URL (yes,
an S3 bucket has both). This commit fixes that behavior.
> Fix redirects on custom domains

- dev-portal/package.json
- lambdas/backend/package.json
- lambdas/catalog-updater/package.json
- lambdas/listener/package.json
- lambdas/static-asset-uploader/package.json
- package.json
This adds the first step towards usable release-tooling. `npm run
get-dependencies` from the top level directory will install dev portal
dependencies, build the dev portal, and install all the lambda
dependencies.
> Add get-dependencies script

- cloudformation/template.yaml
SAR only recognizes custom resources defined as
"AWS::CloudFormation::CustomResource", but we were using the newer,
shorter syntax of "Custom::ArbitraryString".
> Fix SAR blocking issue

- dev-portal/src/components/ApisMenu.jsx
- dev-portal/src/services/api-catalog.js
NOTE: This builds on top of https://github.com/awslabs/aws-api-gateway-developer-portal/pull/156 -- only the commits https://github.com/awslabs/aws-api-gateway-developer-portal/commit/399ed93b2103672152ac3b330f76b7fc5b5eafa8 and https://github.com/awslabs/aws-api-gateway-developer-portal/commit/4568db5ce94892d6d9d9b7e8a33228537b03d0ea are relevant here.
1. correctly select generic APIs if apiGateway apis don't exist
2. refactor apis menu for clarity and better functionality
- removed internal state and returned to functional components
- extracted sub-menu to a new component
- extracted isActive to external function
- display "No APIs Published" correctly
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Api list page fixes

- .travis.yml
- dev-portal/package.json
Also make react-scripts a dev dependency, since it's needed to run
tests.
> Add installing dev dependencies to travis build

- dev-portal/src/components/SwaggerUiLayout.jsx
Hide the version for API Gateway API's b.c the version is a timestamp, and that's not really useful. (Closes #97.)
---
> Remove timestamp or version

- dev-portal/src/services/state.js
- lambdas/backend/catalog/index.js
- lambdas/catalog-updater/__tests__/catalog-updater-test.js
- lambdas/catalog-updater/__tests__/generic-swagger.json
- lambdas/catalog-updater/index.js
- lambdas/static-asset-uploader/index.js
- package-lock.json
Make the generic api catalog object default. (i.e. if we can't match the catalog as an API Gateway API, still include it, just include it as a generic api.)
Also the lock file.
---
> Generic as fallback

- dev-portal/src/pages/Apis.jsx
- dev-portal/src/services/api-catalog.js
- lambdas/catalog-updater/__tests__/catalog-updater-test.js
- lambdas/catalog-updater/index.js
4c20348 - Basically, we were correctly filtering out every non-apigateway api, and then trying to 'tap' on an undefined value. I moved it to always stay an array -- if `filter` finds nothing, it returns a blank array and `forEach` never runs.
db22f0d - The APIs page was still using the flattened list pattern, and was never hitting the error cases. I also changed `updateUsagePlansAndApisList` to set apiList to the default values on fail.
---
> Catalog generation fix

- cloudformation/template.yaml
*Issue #130  , if available:*
Addresses part of issue #130
Organised parameters into ParameterGroups for improved display when deploying the stack via the CloudFormation UI
Fixed an incorrect parameter description
Removed an unused parameter - AWSRegion
> Organise Parameters

- CONTRIBUTING.md
Specify which branch contributors should use to base changes on and for merging into.
#185 
Updated CONTRIBUTING.md to specify branch requirements for contributors
> Add branch specifics to contribution guide

- cloudformation/template.yaml
Deployments with custom domain names were failing because the output
WebsiteURL referenced the (non-existant) DefaultCloudfrontDistribution.
> Fix custom domain name deployments

- cloudformation/template.yaml
The map of Region -> S3 Website URL is defined twice. See above the removed lines.
> Remove duplicate Region -> S3 Website URL mapping

- cloudformation/template.yaml
- dev-portal/src/components/Feedback.jsx
- dev-portal/src/index.js
- dev-portal/src/services/feedback.js
- lambdas/backend/__tests__/feedback-controller-test.js
- lambdas/backend/_common/feedback-controller.js
- lambdas/backend/express-route-handlers.js
- lambdas/backend/express-server.js
- lambdas/static-asset-uploader/index.js
Added the ability for the customers of dev portal owners to provide feedback. Feedback is submitted through a form, stored in a new table in DynamoDB, and the owner is notified via email by subscribing to a new SNS topic. There are 4 commits in this PR:
- __4d96ae5__
- Adds an optional parameter `DevPortalAdminEmail` to the CloudFormation stack which, if provided, creates a DynamoDB table to store customer feedback, an SNS topic to receive email notifications when feedback is submitted, and the necessary permissions and variables to let the frontend do its thing.
- __d880e5d__
- Ensures that a boolean `feedbackEnabled` is written to `config.js` denoting whether or not the dev portal owner has opted into customer feedback by providing …
> Customer feedback mechanism

- cloudformation/template.yaml
- dev-portal/src/services/api.js
- lambdas/backend/__tests__/admin-catalog-visibility-test.js
- lambdas/backend/__tests__/admin-sdk-generation-test.js
- lambdas/backend/express-route-handlers.js
- lambdas/backend/express-server.js
- lambdas/catalog-updater/__tests__/catalog-updater-test.js
- lambdas/catalog-updater/index.js
- lambdas/setup-jest.js
- lambdas/static-asset-uploader/index.js
This adds two new admin API endpoints (/admin/catalog/:id/sdkGeneration).
Additionally, it adds a new file, sdkGeneration.json, in S3 that stores
whether given api-stages or generic apis are enabled for sdk generation.
sdkGeneration.json is read by catalogUpdater to generate the catalog.
The new sdkGeneration endpoints invoke the catalogUpdater lambda function
to cause a fresh catalog to be generated each time an API is enabled or
disabled for catalog generation.
Other changes include updating staticAssetUploader to create an empty
sdkGeneration.json file, fixing tests broken by these changes, and
refactoring catalogUpdater to an async/await style.
> Add admin API for showing & hiding SDK generation

- .travis.yml
So, node v11.11 broke Jest's process.env mocks, as documented here:
https://github.com/facebook/jest/issues/8069
While Jest already has a fix out, CRA hasn't consumed that fix, and has
large, unfriendly warning text about running tests inside CRA using a
higher version of jest than CRA ships with. To get around this, we're
fixing the node version on Travis to v11.10 temporarily, and will
remove that limitation when CRA has consumed Jest's fix.
> Fix test running on CI

- cloudformation/template.yaml
So, S3 has both regional and global endpoints. Regional endpoints look
like 'bucketName.s3-region.amazonaws.com', and the global endpoint looks
like 'bucketName.s3.amazonawas.com'. Earlier, I found out that the
global DNS takes ~40 minutes to propagate, and that time is not tracked
in CloudFormation, so CFN will declare the stack ready before the
CloudFront distribution points to a working origin.
To mitigate that, I moved the stack to using only the regional endpoints.
Unfortunately, us-east-1 never gets a regional DNS (!!!), so in us-east-1  we need
to always use the global endpoint. This change moves to that behavior;
global endpoint in us-east-1 , regional endpoint everywhere else.
By submitting this pull request, I confirm that my contribution is made under …
> Fix IAD S3 bug

- cloudformation/template.yaml
- lambdas/static-asset-uploader/index.js
The stack can be very quickly set up / torn down now using development
mode. This doesn't create a CloudFront distribution, disables OAI,
writes files to the S3 website bucket with a public read ACL, and sets
Cognito's hosted UI to accept localhost and s3 as valid domains, instead
of CloudFront.
> Add development mode as a stack param

- .gitignore
- .travis.yml
- __tests__/cfn-integration-test.js
- package.json
- scripts/test.js
These tests stand the CFN stack up in a region, verify that the
resulting CloudFront distribution is serving the static site's
index.html, and then tears the stack down. It does this in both IAD and
PDX, since we've had issues with S3 regional URLs before.
> Add integ tests for CFN stack standup/teardown

- cloudformation/template.yaml
Issue #255 
When CustomDomainName set, the origin set on the API gateway CORS headers is the CloudFront 
URL not the custom one that the caller will actually be coming from. This fix changes the CORS header
to be the custom URL
> Fix bug where wrong origin set on API CORS policy

- README.md
- cloudformation/template.yaml
- dev-portal/package-lock.json
- dev-portal/src/index.js
*Issue #, if available:* #260 
*Description of changes:* This PR adds a redirect from `/index.html` to `/`, which fixes access to the dev portal via to the `WebsiteURL` CloudFormation output.
> Fix dev mode index html

- package.json
When running `npm run get-dependencies`, I expect all dependencies to be installed so that I can build or test the package. However, because we previously did not run `npm install` as part of this command, some dependencies (such as xml-js) were missing. This PR resolves that issue.
> Run `npm install` upon `npm run get-dependencies`

- README.md
*Description of changes:* This PR reformats the commands in the Setup sections so that they fit in one screen width, and are easier to read.
> Reformat README setup commands

- cloudformation/template.yaml
Issue #247
Added validation for the StaticAssetRebuildMode parameter.
Only allows blank string or the value used by the lambda function.
> Add validation for the rebuild mode CloudFormation template parameter

- cloudformation/template.yaml
Issue #247 
Added validation for the boolean parameters.
Only allows lowercase true or false.
> Add validation for boolean CloudFormation template parameters

- lambdas/backend/_common/customers-controller.js
- lambdas/backend/express-route-handlers.js
- lambdas/backend/shared/get-all-usage-plans.js
- lambdas/catalog-updater/index.js
- lambdas/catalog-updater/shared/get-all-usage-plans.js
- lambdas/shared/__tests__/get-all-usage-plans-test.js
- lambdas/shared/get-all-usage-plans.js
Fixes #257.
Previously, whenever we fetched the list of all usage plans (both in the CatalogUpdaterLambda and in the DevPortalLambda), we only fetched the first page. When there are multiple pages of usage plans, some do not appear in the developer portal frontend, nor in the catalog. This PR resolves that issue.
> Fetch all usage plan pages

- cloudformation/template.yaml
- dev-portal/scripts/dump-v3-account-data.js
- lambdas/common-layer/nodejs/node_modules/dev-portal-common/pager.js
- lambdas/dump-v3-account-data/index.js
- lambdas/jsconfig.json
This PR adds a lambda function (and corresponding script) to dump account data from CustomersTable and from the CognitoUserPool, which will allow Portal owners to migrate their users if they need to change their UserPool in ways which require replacement. 
> Add lambda and script to dump v3 account data

- CONTRIBUTING.md
- cloudformation/template.yaml
- dev-portal/package-lock.json
- dev-portal/package.json
- dev-portal/scripts/dump-v3-account-data.js
- dev-portal/src/__tests__/utils.jsx
- dev-portal/src/components/Admin/Accounts/AccountsTable.jsx
- dev-portal/src/components/Admin/Accounts/AccountsTable.module.css
- dev-portal/src/components/Admin/Accounts/AccountsTableColumns.jsx
- dev-portal/src/components/MessageList.jsx
- dev-portal/src/pages/Admin/Accounts/AccountInvites.jsx
- dev-portal/src/pages/Admin/Accounts/AccountRequests.jsx
- dev-portal/src/pages/Admin/Accounts/AdminAccounts.jsx
- dev-portal/src/pages/Admin/Accounts/RegisteredAccounts.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/RegisteredAccounts.jsx
- dev-portal/src/pages/Admin/Admin.jsx
- dev-portal/src/pages/Admin/SideNav.jsx
- dev-portal/src/pages/__tests__/Home.jsx
- dev-portal/src/services/accounts.js
- dev-portal/src/utils/test-utils.jsx
- lambdas/common-layer/nodejs/node_modules/dev-portal-common/pager.js
- lambdas/dump-v3-account-data/index.js
- lambdas/jsconfig.json
- package-lock.json
- package.json
This PR implements the "Registered Accounts" page for the Dev Portal Account Management dashboard. The diff is big, but the most relevant files are:
- cloudformation/**template.yaml**: Modified to enforce email-address-as-username in the Cognito User Pool.
- dev-portal/src/pages/Admin/Accounts/**RegisteredAccounts.jsx**: The full Registered Accounts list page; wraps the AccountsTable with data fetching and actions/buttons for Delete/Promote functionality.
- dev-portal/src/components/Admin/Accounts/**AccountsTable.jsx**: A reusable table for listing, filtering, and sorting Account data.
---
> Implement "Registered Accounts" admin page

- dev-portal/src/components/Admin/Accounts/AccountsTableColumns.jsx
- dev-portal/src/pages/Admin/Accounts/AccountRequests.jsx
- dev-portal/src/pages/Admin/Accounts/PendingRequests.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/PendingRequests.jsx
- dev-portal/src/pages/Admin/Admin.jsx
- dev-portal/src/services/accounts.js
This PR introduces UI and tests for listing accounts which are pending Admin approval.
> List pending requests UI

- dev-portal/src/components/Admin/Accounts/AccountsTableColumns.jsx
- dev-portal/src/pages/Admin/Accounts/PendingInvites.jsx
- dev-portal/src/pages/Admin/Accounts/PendingRequests.jsx
- dev-portal/src/pages/Admin/Accounts/RegisteredAccounts.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/AdminAccounts.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/PendingInvites.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/PendingRequests.jsx
- dev-portal/src/pages/Admin/Accounts/__tests__/RegisteredAccounts.jsx
- dev-portal/src/services/accounts.js
During front-end development of account management features, we use camelCase for account field names, but in fact we will serve data PascalCased from the backend. Also, we will use `IdentityId` and `UserId` field names, instead of the ambiguous `IdentityPoolId` and `UserPoolId` names. This PR applies these changes to the frontend code, in preparation for integrating with the backend.
> Fix account field names in frontend

- cloudformation/template.yaml
> Add some rudimentary copy for the email

- cloudformation/template.yaml
- lambdas/backend/routes/apikey.js
- lambdas/backend/routes/catalog.js
- lambdas/backend/routes/feedback.js
- lambdas/backend/routes/subscriptions/usage.js
- lambdas/static-asset-uploader/index.js
> Fix asset uploader, tweak backend and dev setup

- dev-portal/src/pages/Admin/ApiManagement.jsx
> Fix file upload iteration

- package-lock.json
- package.json
- scripts/internal/execute-tasks.js
- scripts/internal/util.js
- scripts/run.js
- scripts/test.js
It properly handles color enabling/disabling, among other things.
Also, don't rely on the current working directory in `test.js` - it was
causing errors running it from the root.
> Use Chalk for terminal coloring

- lambdas/backend/routes/admin/catalog/visibility.js
*Description of changes:* Instead of just requesting it blindly, we now loop to ensure we get every API.
> Fix unintended limitation with fetching APIs

- BUILDING.md
- cloudformation/template.yaml
- dev-portal/example-deployer.config.js
- dev-portal/example-dev-deployer.config.js
- scripts/internal/deploy-template.js
- scripts/internal/get-deployer-config.js
- scripts/internal/write-config.js
- scripts/run.js
- Add deployer config options to correspond to the rest of the SAM template.
- Move the deployer config docs from the example deployer script to BUILDING.md in the root.
- Fully document the deployer config file, including the newly added options.
- Link to the example deployer config scripts from the relevant step in BUILDING.md.
- Document the test scripts.
- Recast the deployment config parsing so it's easier to understand. (This helped me tremendously in creating this patch.)
> Fix several issues in BUILDING.md, add missing config options

- dev-portal/src/components/SwaggerUiLayout.jsx
Hide the subscribe button if it's not possible to subscribe (i.e. it doesn't have a Usage Plan.)
---
> hide subscribe button if an API doesn't have a usage plan

- cloudformation/template.yaml
- lambdas/cognito-pre-signup-trigger/index.js
Instead of changing the schema, I'm enforcing it in the lambda, to avoid
Cognito's limitation of not being able to modify existing attributes
on user pools.
> Revert a breaking change to user pools, retain them post-deletion

- BUILDING.md
- BUILDING_SAM.md
- README.md
*Issue #, if available:* #459
- I added a short TOC to make quick navigation easier
- I moved the SAM setup guide to a new page so 1. it's easier to reference and 2. it's easier to skip past if you don't care about it.
- I moved the SAM setup instructions to a separate file and aligned it stylistically with the existing main development guide. I also expanded it to include updating instructions for clarity.
- I clarified the SAM setup a lot - there wasn't any instructions on how to set up the admin account for one, and I also accounted for platform differences some so people aren't tripped up as easily if they just choose to copy and paste or if they're still not super familiar with the terminal. Just a little extra hand holding.
- I fixed the alt text for the …
> Redo building + setup docs for clarity, delegate more to the AWS-side docs

- BUILDING.md
- dev-portal/example-deployer.config.js
- dev-portal/example-dev-deployer.config.js
- scripts/internal/deploy-template.js
- scripts/internal/get-deployer-config.js
*Issue #, if available:* https://github.com/awslabs/aws-api-gateway-developer-portal/issues/488#issuecomment-914292194 (possibly)
*Description of changes:* Title's pretty obvious, as is the patch. Won't require a new release as it only touches dev scripts.
> Add new `region` key to allow deploying to alternate regions explicitly

- dev-portal/package-lock.json
- dev-portal/package.json
- package-lock.json
Fix security issues related to `node-forge`. `node-forge` is a dependency pulled in by `react-scripts`, the security fix is in `node-forge v1.3.0` which is available in `react-scripts v5.0.0`.
Also includes other medium security fixes run by `npm audit fix`
> Upgrade react-script to pull in newer version of node-forge to fix security related issues

- dev-portal/node_modules/swagger-ui/package.json
- dev-portal/package-lock.json
- dev-portal/package.json
Fix security issues related to `sanitize-url`.  The dependency is fixed in `swagger-ui`, and now we are just picking it up.
> Pick up latest security fix in forked swagger-ui branch

- scripts/internal/util.js
This fixes an issue where child processes are not being correctly spawned on Windows. 
Documentation can be found here:
https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#spawning-bat-and-cmd-files-on-windows
> Add shell to spawn to support Windows
