dev-portal/public/apigateway-js-sdk/README.md

I could see some people getting tripped up by this (since the code sample is different than the default).

Make example region the same as the default

---

scripts/pre-configure.js

Added the choice for ap-southeast-2 as it works there.

Added sydney region as a region choice.

---

dev-portal/src/components/ApiCatalog/index.js
dev-portal/src/components/App/App.css
dev-portal/src/components/App/index.js
dev-portal/src/components/Head/index.js
dev-portal/src/pages/Home.js

Layout changes to be staged together with the sam updates by Ashton
1) Added sidebar -> made redundant (for current use cases) so removed for now
2) Added logout functionality to landing page by including header
3) Misc layout fixes: smaller header, smaller cards, background color of header to black, replaced container with div to fix spacing issue

Sam layout updates

---

README.md
cloudformation/template.yaml

Update README and SAM template descriptions

---

README.md
cloudformation/template.yaml
lambdas/backend/catalog/PestStore-prod-swagger-apigateway.json
lambdas/backend/catalog/PetStore-asfd-swagger-apigateway.json
lambdas/static-asset-uploader/index.js
package.json

The changes to move to SAM broke the marketplace integration. This
commit should fix them by making the marketplace SNS topic available in
the config object. Also includes some housecleaning (removing unecessary
bits of package.json, cleaning up README markdown syntax).

Update marketplace integration

---

README.md
lambdas/catalog-updater/index.js

Intent is to support windows filesystems.

Move to API_STAGE instead of API:STAGE

---

lambdas/static-asset-uploader/index.js

It was re-using (???) the through pipe on re-uploads if the lambda was
still warm, causing the through pipe to fail with a write-after-end
error. Really unsettling; we should understand why this happens.

Fix odd edge case with static asset uploader

---

cloudformation/template.yaml

Split lambda execution roles apart

---

lambdas/catalog-updater/index.js
lambdas/catalog-updater/package.json

YAML & OAS 3 support

---

cloudformation/template.yaml
dev-portal/package.json
dev-portal/scripts/write-config.js

Simplify CFN stack outputs

---

lambdas/static-asset-uploader/index.js

Config.js should be logged for easier debugging.

Improve logging in static asset uploader

---

dev-portal/scripts/write-config.js
dev-portal/src/components/ApisMenu.jsx
dev-portal/src/components/SwaggerUiLayout.jsx
lambdas/catalog-updater/index.js

First commit:
- Move conditional check for generic API to top of if/else block
- write-config was broken due to L32; slight refactor
Second commit:
UI fixes as per Alan:
- Header color in API side nav
- Update text
- Align side nav w/ header

fix(Generic Swagger, write-config)

---

dev-portal/src/pages/Dashboard.jsx
dev-portal/src/services/api-catalog.js
dev-portal/src/services/misc.js

- add remaining metrics to usage graphs
- add limit indicator above usage graphs

update graphs to have remaining limits on them

---

dev-portal/src/components/NavBar.jsx
dev-portal/src/services/self.js
dev-portal/src/services/state.js

Fix navbar refresh

---

dev-portal/src/components/ApisMenu.jsx

Fixes the coloring of the sidebar.

fix sidebar to use lightsteelblue coloring

---

.travis.yml

*Description of changes:* Adds a `.travis.yml` file to enable CI testing. Will add CD builds later.

Add basic Travis integration

---

dev-portal/src/services/self.js
dev-portal/src/services/state.js

Fixes:
- the dev portal will now display an error instead of pretending that you logged in successfully if using an invalid email
- clear the store on log out (clears API keys, usage data, apis, etc,.)
- update store on log in (API Key, usage data, etc,.)
---

bug fixes related to sign in/out states

---

.travis.yml

Install all dev portal dependencies and cache results

---

dev-portal/README.md

Clarify first time setup steps to get local development running.
Closes #166. Also closes #161.

Update dev portal README

---

dev-portal/src/pages/Apis.jsx

Don't authorize unless we actually have an api key.
---

Authorize "Try It Out" only if we actually have a key

---

lambdas/backend/catalog/index.js
lambdas/catalog-updater/index.js
lambdas/static-asset-uploader/index.js

Found some bugs in the refactor. Exterminated them.
---

fix some build failures in static asset uploader

---

dev-portal/src/services/state.js
lambdas/backend/catalog/index.js
lambdas/catalog-updater/index.js
lambdas/static-asset-uploader/index.js

Store wasn't correctly reacting. Apparently the 'returns' checks reference and not the actual value. Might be a good idea to add some diff checker to reactTo. Later, though.
---

tweak to make sure the apis list fires a reaction on updates

---

dev-portal/src/pages/Dashboard.jsx

Don't try to render a graph that has no apis. (Better than the alternative -- show a graph that has no title.)
---

fix dashboard no apis edge case

---

lambdas/catalog-updater/__tests__/catalog-updater-test.js
lambdas/catalog-updater/__tests__/oas3-ANY+GET-methods.json
lambdas/catalog-updater/__tests__/oas3-ANY-method.json
lambdas/catalog-updater/__tests__/swagger-ANY+GET-methods.json
lambdas/catalog-updater/__tests__/swagger-ANY-method.json
lambdas/catalog-updater/index.js

update catalog-updater to convert any method to all other undefined methods (closes #101)
---

Add Support for ANY

---

cloudformation/template.yaml

Fix S3 website URLs. Closes #151.

Website url

---

cloudformation/template.yaml

#129 
If a custom domain is givin, create an Output for it for easy reference

Output CustomDomainName if configured.

---

README.md

Add steps for updating to a new version

Add steps for Update

---

cloudformation/template.yaml

Now needs more characters and requires at least 1 lowercase character
and 1 number.

Increase password requirements

---

cloudformation/template.yaml
dev-portal/README.md
dev-portal/package-lock.json
dev-portal/package.json
dev-portal/scripts/delete-matching-logGroups.js
dev-portal/scripts/deploy-stack.js
dev-portal/scripts/write-config.js
dev-portal/src/components/NavBar.jsx
dev-portal/src/index.js
dev-portal/src/services/api.js
dev-portal/src/services/self.js
lambdas/cfn-cognito-user-pools-client-settings/index.js
lambdas/cfn-cognito-user-pools-client-settings/notify-cfn.js
lambdas/cfn-cognito-user-pools-domain/index.js
lambdas/cfn-cognito-user-pools-domain/notify-cfn.js
lambdas/shared/notify-cfn.js
lambdas/static-asset-uploader/index.js

Closes #204
Add support for Cognito Hosted UI. Users can provide a new parameter (CognitoDomainNameOrPrefix) to define a domain name prefix. Custom Domain Name support not yet included.
Note: Needs unit tests.
---

Add support for Cognito Hosted UI.

---

cloudformation/template.yaml

Fix template not deploying

---

dev-portal/src/services/self.js

Fixes #218 
There's some other minor auth-related fixes here, too.
---

Fix minor sign in bugs

---

.gitignore
dev-portal/node_modules/swagger-ui/package.json
dev-portal/package.json

Fix SwaggerUIv3 assets from being overwritten on npm install.

Swagger ui3

---

cloudformation/template.yaml
dev-portal/jsconfig.json
dev-portal/src/components/NavBar.jsx
dev-portal/src/services/self.js
lambdas/backend/__tests__/admin-catalog-visibility-test.js
lambdas/backend/catalog/index.js
lambdas/backend/express-route-handlers.js
lambdas/backend/express-server.js
lambdas/cfn-cognito-user-pools-client-settings/index.js
lambdas/cfn-cognito-user-pools-client-settings/notify-cfn.js
lambdas/cfn-cognito-user-pools-domain/notify-cfn.js
lambdas/static-asset-uploader/__tests__/asset-uploader-test.js
lambdas/static-asset-uploader/index.js
lambdas/static-asset-uploader/notify-cfn.js
lambdas/static-asset-uploader/package.json

Add OAuth auth, then remove it, then add Groups auth. This involves enough removing/adding that file-diff view may be more helpful than by-commit view.

Groups auth

---

dev-portal/src/components/Feedback.jsx

Move feedback button further down the page

---

cloudformation/template.yaml
lambdas/cfn-cognito-user-pools-client-settings/index.js

Fix deployment for development mode

---

README.md

Fixing deadlink

---

lambdas/static-asset-uploader/index.js

This PR fixes a few error handling cases in the static asset uploader lambda.

Fix some asset uploader error cases

---

CONTRIBUTING.md
package-lock.json
package.json

This PR adds Prettier to the dev-dependencies, along with configuration that closely matches the existing style.

Add and configure Prettier

---

package.json

This PR fixes a few misquoted prettier config values.

Fix malformed prettier config

---

CODEOWNERS

Add myself to the list of code owners

---

dev-portal/src/components/SwaggerUiLayout.jsx

Continuation of #354 (closed due to my own error)

Add description

---

lambdas/backend/index.js

Continuation of #356 (closed due to my own error)

Increase limit to allow for larger API imports/etc.

---

dev-portal/src/components/SwaggerUiLayout.jsx

Hide description field when no description exists

---

dev-portal/src/components/ApisMenu.jsx

Show stage names with APIs

---

dev-portal/src/components/SwaggerUiLayout.jsx
lambdas/backend/__tests__/routes/accounts.js
lambdas/backend/index.js
lambdas/backend/routes/accounts.js
lambdas/backend/routes/accounts/promoteToAdmin.js
lambdas/backend/routes/signin.js
lambdas/backend/util.js
lambdas/common-layer/nodejs/node_modules/dev-portal-common/customers-controller.js
lambdas/setup-jest.js
lambdas/shared/__tests__/customers-controller.js

- Unbreak accounts and write tests for the relevant bits so they won't break later.
- I noticed I forgot to push an intended message tweak in #362 (the first commit in this) and so I included that in this PR.

Fix broad brokenness with account management

---

lambdas/backend/__tests__/routes/catalog/export.js
lambdas/backend/routes/catalog/export.js

Fix corrupted export functionality

---

dev-portal/src/components/GetSdk.jsx

Add a missing comma

---

dev-portal/src/pages/Admin/ApiManagement.jsx
dev-portal/src/pages/Dashboard.jsx

Add a couple loading spinners

---

dev-portal/src/services/state.js

Fix an image URL

---

dev-portal/README.md
dev-portal/scripts/deploy-stack.js
dev-portal/scripts/deploy-template.js

Tweak the dev setup a little

---

dev-portal/src/services/accounts.js
lambdas/backend/__tests__/routes/admin/accounts.js
lambdas/backend/index.js
lambdas/backend/routes/admin/accounts.js

Tweak accounts

---

cloudformation/template.yaml
package-lock.json
package.json
scripts/internal/color.js
scripts/internal/execute-tasks.js
scripts/internal/supports-color.js
scripts/internal/util.js
scripts/run.js

Fix bucket permissions

---

cloudformation/template.yaml

Fix Node environment for lambdas, set backend to production

---

README.md

Fix an incorrect link. That's it.
---

fix the sam cli install link

---

lambdas/backend/index.js

Hide the user registration request routes

---

lambdas/common-layer/nodejs/node_modules/dev-portal-common/customers-controller.js
lambdas/shared/__tests__/customers-controller.js

Fix admin promotion to actually be idempotent

---

dev-portal/example-deployer.config.js
dev-portal/src/components/Feedback.jsx

Fix typo in feedback

---

dev-portal/src/components/NavBar.jsx
dev-portal/src/services/self.js
dev-portal/src/services/state.js

Put username in navbar.
Additional changes:
- also rename unused `cognitoUser` to `user`
- clarified some of the auth functions use and when they happen
---

add username to the signout button

---

lambdas/backend/routes/admin/catalog/visibility.js

Fix the admin panel's visibility buttons for non-sub APGWI apis.
---

fix the admin panel's visibility buttons for non-sub APGWI apis

---

lambdas/backend/__tests__/routes/admin/catalog/visibility.js
lambdas/backend/routes/admin/catalog/visibility.js

Offer a workaround in case an API has a usage plan added after it's displayed

---

dev-portal/src/components/Admin/Accounts/AccountsTable.jsx
dev-portal/src/components/Admin/Accounts/AccountsTableColumns.jsx
dev-portal/src/pages/Admin/Accounts/RegisteredAccounts.jsx
dev-portal/src/services/accounts.js
lambdas/backend/routes/admin/accounts.js

- display if users are admins in the registered table
- disable the promote button for existing admins
- indicate in the table which user you are
- disable the delete button if you're trying to delete yourself
- add BIG RED warning indicator to the modal if you're deleting an admin
---

made users experience better WRT admins

---

cloudformation/template.yaml

Prevent exposing the existence of users from the login page

---

README.md
cloudformation/template.yaml
lambdas/user-group-exporter-v3/index.js
lambdas/user-group-importer/index.js
lambdas/user-group-importer/node_modules/node-fetch/CHANGELOG.md
lambdas/user-group-importer/node_modules/node-fetch/LICENSE.md
lambdas/user-group-importer/node_modules/node-fetch/README.md
lambdas/user-group-importer/node_modules/node-fetch/browser.js
lambdas/user-group-importer/node_modules/node-fetch/lib/index.es.js
lambdas/user-group-importer/node_modules/node-fetch/lib/index.js
lambdas/user-group-importer/node_modules/node-fetch/lib/index.mjs
lambdas/user-group-importer/node_modules/node-fetch/package.json
lambdas/user-group-importer/package-lock.json
lambdas/user-group-importer/package.json

Add importer + exporter

---

cloudformation/template.yaml
lambdas/backend/index.js

Backend fix

---

lambdas/static-asset-uploader/index.js

#431
add .promise where necessary

fix issue #431

---

cloudformation/template.yaml
lambdas/backend/__tests__/routes/admin/catalog/sdkGeneration.js
lambdas/backend/__tests__/routes/admin/catalog/visibility.js
lambdas/backend/__tests__/util.js
lambdas/backend/routes/admin/catalog/sdkGeneration.js
lambdas/backend/routes/admin/catalog/visibility.js
lambdas/backend/util.js
lambdas/catalog-updater/__tests__/catalog-updater-test.js
lambdas/catalog-updater/index.js
lambdas/static-asset-uploader/__tests__/asset-uploader-test.js
lambdas/static-asset-uploader/index.js
lambdas/user-group-exporter-v3/index.js
lambdas/user-group-importer/index.js

Added ExpectedBucketOwner params to the backend lambdas. Also updated the tests

Bucket Sniping Fix

---

cloudformation/template.yaml
lambdas/cloudfront-security/replicator.js

*Issue #519 *
Adding waiter for Lambda Function steps

Fix Issue 519

---

README_SAR.md

*Issue #, if available:* None
Found text pointing to dead link. I am guessing it was for developer portal's home screen - so updated the same.

Add right home screen image link
